name: Render Page
on: push
permissions:
  contents: write
jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://bosschaert/sling-mini-offline:4
        env:
          SOURCE_DIR: ${{ github.workspace }}/src/md
          TARGET_DIR: ${{ github.workspace }}/docs
        with:
          entrypoint: /bin/bash
          args: '-c "cd /root && ./launch-offline-bare.sh"'

      - run: ls /home/runner/work/sling-lambda/sling-lambda/docs || true

      - name: Commit and push changes
        run: |
          git config --global user.name 'David Bosschaert'
          git config --global user.email 'david.bosschaert@gmail.com'
          git add docs
          git commit -m "Rendered pages in run $GITHUB_RUN_ID"
          git push
