name: Render Page
on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker://bosschaert/sling-mini-offline:2
        env:
          SOURCE_DIR: /src/md
          TARGET_DIR: /github/home

      - run: ls /home/runner/work/sling-lambda/sling-lambda || true


      # - run: |
      #     ls /tmp/docs && cd /root && ./launch-offline-bare.sh
      # name: Render
      # - run: ls ${{ github.workspace }}
      # - run: ls ${{ github.workspace }}/src/md
      # - run: ls /
      # - run: ls /tmp/docs
      # - uses: docker://bosschaert/sling-mini-offline:1
      # with:
      #   entrypoint: /bin/bash
      #   args: '-c "du /"'

      # with:
      #   entrypoint: /bin/bash
      # args: '-c "ls ./src/md && echo foo > /github/workspace/foo.txt && env | sort"'
