name: Render Pages
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
    steps:
      - uses: actions/checkout@v4

      - name: Clear old docs
        run: ls $GITHUB_WORKSPACE/docs && rm $GITHUB_WORKSPACE/docs/* || true

      - uses: docker://bosschaert/sling-mini-offline:5
        env:
          SOURCE_DIR: ${{ github.workspace }}/src/md
          TARGET_DIR: ${{ github.workspace }}/docs
        with:
          entrypoint: /bin/bash
          args: '-c "cd /root && ./launch-offline-bare.sh"'

      - run: ls /home/runner/work/sling-lambda/sling-lambda/docs || true

      - name: Commit and push changes
        run: |
          git config --global user.name 'David Bosschaert'
          git config --global user.email 'david.bosschaert@gmail.com'
          git add docs
          git commit -m "Rendered pages in run $GITHUB_RUN_ID" || true
          git push || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs

      - uses: actions/deploy-pages@v4


