name: Render Page
on:
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker://bosschaert/sling-mini-offline:1
        with:
          entrypoint: /bin/bash
          args: du /

      - run: ls /files || true
      - run: ls /src/md || true
      - run: ls /tmp/docs || true


      # - run: |
      #     ls /tmp/docs && cd /root && ./launch-offline-bare.sh
      # name: Render
      # - run: ls ${{ github.workspace }}
      # - run: ls ${{ github.workspace }}/src/md
      # - run: ls /
      # - run: ls /tmp/docs