name: Render Pages
on: push
jobs:
  render:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Clear old docs
        run: rm $GITHUB_WORKSPACE/docs/* || true

      - uses: docker://bosschaert/sling-mini-offline:5
        env:
          SOURCE_DIR: ${{ github.workspace }}/src/md
          TARGET_DIR: ${{ github.workspace }}/docs
        with:
          entrypoint: /bin/bash
          args: '-c "cd /root && ./launch-offline-bare.sh"'

      - name: Commit and push changes
        run: |
          git config --global user.name 'David Bosschaert'
          git config --global user.email 'david.bosschaert@gmail.com'
          git add docs
          git commit -m "Rendered pages in run $GITHUB_RUN_ID" || true
          git push || true

      - uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/docs

      - uses: actions/deploy-pages@v4

      - name: Publish to Helix
        run: |
          UPDATED_FILES=$(git diff-tree --no-commit-id --name-only `git rev-parse HEAD` -r)
          for FPATH in ${UPDATED_FILES}; do
              echo Changed file: "$FPATH"
              if [[ $FPATH == *.md.html ]]
              then
                  # Remove docs/prefix
                  FNAME="${FPATH##docs/}"
                  # Remove file extension
                  FBASE="${FNAME%%.*}"
                  echo Previewing and publishing content file: $FBASE

                  # Preview to Helix
                  curl -X POST https://admin.hlx.page/preview/bosschaert/sling-lambda-site/main/$FBASE
                  # Publish to Helix
                  curl -X POST https://admin.hlx.page/live/bosschaert/sling-lambda-site/main/$FBASE
              fi
          done

